#! /bin/bash
# Copyright (c) 2020 Till Maas <opensource@till.name>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

set -e

if [[ "${#}"  -lt 3 ]]
then
    echo "USAGE: ${0} name srcdisk os_variant"
    echo "Get os_variant names with 'osinfo-query os', examples: "
    echo "fedora35, rhel8.6, centos-stream8, ubuntu19.10"
    exit 1
fi

name="${1}"
srcdisk="${2}"

libvirtbase="$HOME/.local/share/libvirt/images/"

disk="${libvirtbase}/${name}_${srcdisk##*/}"
cloudinit="${libvirtbase}/${disk##*/}-cloudinit.iso"

cp --no-clobber "${srcdisk}" "${disk}"
qemu-img resize "${disk}" +5G

os_variant="${3}"

mkcloudinit --hostname "${name}" "${cloudinit}"
virt-install --import --name "${name}" --ram 2048 --vcpus 1 --disk "${disk}",format=qcow2,bus=virtio --disk "${cloudinit}",device=cdrom --network bridge=virbr0,model=virtio --controller scsi,model=virtio-scsi --os-variant="${os_variant}" --graphics spice --noautoconsole --check path_in_use=off
