#!/usr/bin/bash
# Copyright (c) 2020 Till Maas <opensource@till.name>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

internal="eDP-1"


if xrandr | grep -q "^DP[^ ]* connected"
then
    acer="$(xrandr | grep "^DP[^ ]* connected" | cut -d" " -f 1)"
else
    acer="HDMI-2"
fi

setup_acer() {
    for m in c l r
    do
        xrandr --delmonitor "$m"
    done
    # P1 Gen 4 needs this to cycle the output once to get it back on
    #xrandr --output "${acer}" --off
    xrandr --output "${internal}" --off --output "${acer}" --primary --auto
    #xrandr --output "${internal}" --auto --output "${acer}" --primary --auto

    xrandr --setmonitor c 1840/376x1600/367+1000+0 "${acer}"
    xrandr --setmonitor l 1000/252x1600/367+0+0 none
    xrandr --setmonitor r 1000/252x1600/367+2840+0 none

    # for ws in 1 2 3
    # do
    #     i3-msg "[workspace=$ws] move workspace to output l"
    # done
    #
    # for ws in 4 5 6 7
    # do
    #     i3-msg "[workspace=$ws] move workspace to output c"
    # done
    #
    # for ws in 8 9 10
    # do
    #     i3-msg "[workspace=$ws] move workspace to output r"
    # done
}


setup_dual() {
    for m in c l r
    do
        xrandr --delmonitor "$m"
    done

    xrandr --output "${internal}" --off --output "${acer}" --primary --auto
    #xrandr --output "${internal}" --auto --output "${acer}" --primary --auto

    xrandr --setmonitor l 1920/440x1600/367+0+0 "${acer}"
    xrandr --setmonitor r 1920/440x1600/367+1920+0 none

    for ws in 1 2 3 4 5
    do
        i3-msg "[workspace=$ws] move workspace to output l"
    done

    for ws in 6 7 8 9 10
    do
        i3-msg "[workspace=$ws] move workspace to output r"
    done
}

setup_internal()
{
    # xrandr --output "${acer}" --off --output "${internal}" --primary --auto
    #xrandr --output "${internal}" --primary --auto --output "${acer}" --same-as "${internal}"
    acer="$(xrandr | grep ^DP- | grep 3840x1600 | cut -d" " -f 1)"
    xrandr --output "${internal}" --primary --auto --scale 0.75 --output "${acer}" --off

    for m in c l r
    do
        xrandr --delmonitor "$m"
    done
}

mode="${0##*xrandr-}"

if [[ "${mode}" == "acer" ]]
then
    setup_acer
elif [[ "${mode}" == "dual" ]]
then
    setup_dual
elif [[ "${mode}" == "internal" ]]
then
    setup_internal
else
    exit 1
fi

xset r rate 220 45
i3-msg restart
